# Generated by Django 3.2 on 2021-04-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0003_banner_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=200)),
                ('is_checked', models.BooleanField(default=False)),
                ('send_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
